spring:
  application:
    name: teachmon-local
  config:
    import:
      - optional:file:env/local.env[.properties]
  datasource:
    driver-class-name:
      ${POSTGRES_DRIVER_NAME}
    url:
      ${POSTGRES_URL}
    username:
      ${POSTGRES_USERNAME}
    password:
      ${POSTGRES_ROOT_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
  cloud:
    openfeign:
      okhttp:
        enabled: true
      http2client:
        enabled: true
      httpclient:
        hc5:
          enabled: true

oauth2:
  google:
    service-name: google
    base-url: ${OAUTH2_BASE_URL}
    client-id: ${OAUTH2_CLIENT_ID}
    client-secret: ${OAUTH2_CLIENT_SECRET}
    redirect-uri: ${OAUTH2_REDIRECT_URI}
    grant-type: ${OAUTH2_GRANT_TYPE}
    response-type: code
    scopes:
      - https://www.googleapis.com/auth/userinfo.email
      - https://www.googleapis.com/auth/userinfo.profile

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
